use super::*;

define_av_alias! {
	#[repr(u32)]
	#[bitflags]
	pub enum PacketFlag {
		Keyframe   = AV_PKT_FLAG_KEY as u32,
		Corrupt    = AV_PKT_FLAG_CORRUPT as u32,
		Discard    = AV_PKT_FLAG_DISCARD as u32,
		Trusted    = AV_PKT_FLAG_TRUSTED as u32,
		Disposable = AV_PKT_FLAG_DISPOSABLE as u32
	}
}

define_av_alias! {
	#[repr(u32)]
	#[bitflags]
	pub enum FrameFlag {
		Corrupt    = AV_FRAME_FLAG_CORRUPT as u32,
		Key        = AV_FRAME_FLAG_KEY as u32,
		Discard    = AV_FRAME_FLAG_DISCARD as u32,
		Interlaced = AV_FRAME_FLAG_INTERLACED as u32
	}
}

define_av_alias_casts! {
	#[repr(i32)]
	pub enum SampleFormat = AVSampleFormat {
		#[default]
		None = AVSampleFormat::AV_SAMPLE_FMT_NONE as i32,

		/* packed types */
		U8   = AVSampleFormat::AV_SAMPLE_FMT_U8 as i32,
		I16  = AVSampleFormat::AV_SAMPLE_FMT_S16 as i32,
		I32  = AVSampleFormat::AV_SAMPLE_FMT_S32 as i32,
		F32  = AVSampleFormat::AV_SAMPLE_FMT_FLT as i32,
		F64  = AVSampleFormat::AV_SAMPLE_FMT_DBL as i32,

		/* planar types */
		U8P  = AVSampleFormat::AV_SAMPLE_FMT_U8P as i32,
		I16P = AVSampleFormat::AV_SAMPLE_FMT_S16P as i32,
		I32P = AVSampleFormat::AV_SAMPLE_FMT_S32P as i32,
		F32P = AVSampleFormat::AV_SAMPLE_FMT_FLTP as i32,
		F64P = AVSampleFormat::AV_SAMPLE_FMT_DBLP as i32,

		I64  = AVSampleFormat::AV_SAMPLE_FMT_S64 as i32,
		I64P = AVSampleFormat::AV_SAMPLE_FMT_S64P as i32
	}
}

define_av_alias! {
	#[repr(u64)]
	#[derive(Default, FromPrimitive)]
	pub enum Channel {
		#[default]
		Unknown             = 0,
		FrontLeft           = AV_CH_FRONT_LEFT,
		FrontRight          = AV_CH_FRONT_RIGHT,
		FrontCenter         = AV_CH_FRONT_CENTER,
		LowFrequency        = AV_CH_LOW_FREQUENCY,
		BackLeft            = AV_CH_BACK_LEFT,
		BackRight           = AV_CH_BACK_RIGHT,
		FrontLeftOfCenter   = AV_CH_FRONT_LEFT_OF_CENTER,
		FrontRightOfCenter  = AV_CH_FRONT_RIGHT_OF_CENTER,
		BackCenter          = AV_CH_BACK_CENTER,
		SideLeft            = AV_CH_SIDE_LEFT,
		SideRight           = AV_CH_SIDE_RIGHT,
		TopCenter           = AV_CH_TOP_CENTER,
		TopFrontLeft        = AV_CH_TOP_FRONT_LEFT,
		TopFrontCenter      = AV_CH_TOP_FRONT_CENTER,
		TopFrontRight       = AV_CH_TOP_FRONT_RIGHT,
		TopBackLeft         = AV_CH_TOP_BACK_LEFT,
		TopBackCenter       = AV_CH_TOP_BACK_CENTER,
		TopBackRight        = AV_CH_TOP_BACK_RIGHT,
		StereoLeft          = AV_CH_STEREO_LEFT,
		StereoRight         = AV_CH_STEREO_RIGHT,
		WideLeft            = AV_CH_WIDE_LEFT,
		WideRight           = AV_CH_WIDE_RIGHT,
		SurroundDirectLeft  = AV_CH_SURROUND_DIRECT_LEFT,
		SurroundDirectRight = AV_CH_SURROUND_DIRECT_RIGHT,
		LowFrequency2       = AV_CH_LOW_FREQUENCY_2,
		TopSideLeft         = AV_CH_TOP_SIDE_LEFT,
		TopSideRight        = AV_CH_TOP_SIDE_RIGHT,
		BottomFrontCenter   = AV_CH_BOTTOM_FRONT_CENTER,
		BottomFrontLeft     = AV_CH_BOTTOM_FRONT_LEFT,
		BottomFrontRight    = AV_CH_BOTTOM_FRONT_RIGHT
	}
}

define_av_alias_casts! {
	#[repr(u32)]
	pub enum PictureType = AVPictureType {
		#[default]
		None               = AVPictureType::AV_PICTURE_TYPE_NONE as u32,
		Intra              = AVPictureType::AV_PICTURE_TYPE_I as u32,
		Predicted          = AVPictureType::AV_PICTURE_TYPE_P as u32,
		BidirPredicted     = AVPictureType::AV_PICTURE_TYPE_B as u32,
		Switching          = AVPictureType::AV_PICTURE_TYPE_S as u32,
		SwitchingIntra     = AVPictureType::AV_PICTURE_TYPE_SI as u32,
		SwitchingPredicted = AVPictureType::AV_PICTURE_TYPE_SP as u32,
		BI                 = AVPictureType::AV_PICTURE_TYPE_BI as u32
	}
}

define_av_alias_casts! {
	#[repr(i32)]
	pub enum MediaType = AVMediaType {
		#[default]
		Unknown    = AVMediaType::AVMEDIA_TYPE_UNKNOWN as i32,
		Video      = AVMediaType::AVMEDIA_TYPE_VIDEO as i32,
		Audio      = AVMediaType::AVMEDIA_TYPE_AUDIO as i32,
		Data       = AVMediaType::AVMEDIA_TYPE_DATA as i32,
		Subtitle   = AVMediaType::AVMEDIA_TYPE_SUBTITLE as i32,
		Attachment = AVMediaType::AVMEDIA_TYPE_ATTACHMENT as i32
	}
}

define_av_alias_casts! {
	#[repr(i32)]
	#[allow(clippy::upper_case_acronyms)]
	pub enum PixelFormat = AVPixelFormat {
		#[default]
		None          = AVPixelFormat::AV_PIX_FMT_NONE as i32,
		YUV420P       = AVPixelFormat::AV_PIX_FMT_YUV420P as i32,
		YUYV422       = AVPixelFormat::AV_PIX_FMT_YUYV422 as i32,
		RGB24         = AVPixelFormat::AV_PIX_FMT_RGB24 as i32,
		BGR24         = AVPixelFormat::AV_PIX_FMT_BGR24 as i32,
		YUV422P       = AVPixelFormat::AV_PIX_FMT_YUV422P as i32,
		YUV444P       = AVPixelFormat::AV_PIX_FMT_YUV444P as i32,
		YUV410P       = AVPixelFormat::AV_PIX_FMT_YUV410P as i32,
		YUV411P       = AVPixelFormat::AV_PIX_FMT_YUV411P as i32,
		GRAY8         = AVPixelFormat::AV_PIX_FMT_GRAY8 as i32,
		MONOWHITE     = AVPixelFormat::AV_PIX_FMT_MONOWHITE as i32,
		MONOBLACK     = AVPixelFormat::AV_PIX_FMT_MONOBLACK as i32,
		PAL8          = AVPixelFormat::AV_PIX_FMT_PAL8 as i32,
		YUVJ420P      = AVPixelFormat::AV_PIX_FMT_YUVJ420P as i32,
		YUVJ422P      = AVPixelFormat::AV_PIX_FMT_YUVJ422P as i32,
		YUVJ444P      = AVPixelFormat::AV_PIX_FMT_YUVJ444P as i32,
		UYVY422       = AVPixelFormat::AV_PIX_FMT_UYVY422 as i32,
		UYYVYY411     = AVPixelFormat::AV_PIX_FMT_UYYVYY411 as i32,
		BGR8          = AVPixelFormat::AV_PIX_FMT_BGR8 as i32,
		BGR4          = AVPixelFormat::AV_PIX_FMT_BGR4 as i32,
		BGR4Byte      = AVPixelFormat::AV_PIX_FMT_BGR4_BYTE as i32,
		RGB8          = AVPixelFormat::AV_PIX_FMT_RGB8 as i32,
		RGB4          = AVPixelFormat::AV_PIX_FMT_RGB4 as i32,
		RGB4Byte      = AVPixelFormat::AV_PIX_FMT_RGB4_BYTE as i32,
		NV12          = AVPixelFormat::AV_PIX_FMT_NV12 as i32,
		NV21          = AVPixelFormat::AV_PIX_FMT_NV21 as i32,
		ARGB          = AVPixelFormat::AV_PIX_FMT_ARGB as i32,
		RGBA          = AVPixelFormat::AV_PIX_FMT_RGBA as i32,
		ABGR          = AVPixelFormat::AV_PIX_FMT_ABGR as i32,
		BGRA          = AVPixelFormat::AV_PIX_FMT_BGRA as i32,
		GRAY16BE      = AVPixelFormat::AV_PIX_FMT_GRAY16BE as i32,
		GRAY16LE      = AVPixelFormat::AV_PIX_FMT_GRAY16LE as i32,
		YUV440P       = AVPixelFormat::AV_PIX_FMT_YUV440P as i32,
		YUVJ440P      = AVPixelFormat::AV_PIX_FMT_YUVJ440P as i32,
		YUVA420P      = AVPixelFormat::AV_PIX_FMT_YUVA420P as i32,
		RGB48BE       = AVPixelFormat::AV_PIX_FMT_RGB48BE as i32,
		RGB48LE       = AVPixelFormat::AV_PIX_FMT_RGB48LE as i32,
		RGB565BE      = AVPixelFormat::AV_PIX_FMT_RGB565BE as i32,
		RGB565LE      = AVPixelFormat::AV_PIX_FMT_RGB565LE as i32,
		RGB555BE      = AVPixelFormat::AV_PIX_FMT_RGB555BE as i32,
		RGB555LE      = AVPixelFormat::AV_PIX_FMT_RGB555LE as i32,
		BGR565BE      = AVPixelFormat::AV_PIX_FMT_BGR565BE as i32,
		BGR565LE      = AVPixelFormat::AV_PIX_FMT_BGR565LE as i32,
		BGR555BE      = AVPixelFormat::AV_PIX_FMT_BGR555BE as i32,
		BGR555LE      = AVPixelFormat::AV_PIX_FMT_BGR555LE as i32,
		VAAPI         = AVPixelFormat::AV_PIX_FMT_VAAPI as i32,
		YUV420P16LE   = AVPixelFormat::AV_PIX_FMT_YUV420P16LE as i32,
		YUV420P16BE   = AVPixelFormat::AV_PIX_FMT_YUV420P16BE as i32,
		YUV422P16LE   = AVPixelFormat::AV_PIX_FMT_YUV422P16LE as i32,
		YUV422P16BE   = AVPixelFormat::AV_PIX_FMT_YUV422P16BE as i32,
		YUV444P16LE   = AVPixelFormat::AV_PIX_FMT_YUV444P16LE as i32,
		YUV444P16BE   = AVPixelFormat::AV_PIX_FMT_YUV444P16BE as i32,
		DXVA2Vld      = AVPixelFormat::AV_PIX_FMT_DXVA2_VLD as i32,
		RGB444LE      = AVPixelFormat::AV_PIX_FMT_RGB444LE as i32,
		RGB444BE      = AVPixelFormat::AV_PIX_FMT_RGB444BE as i32,
		BGR444LE      = AVPixelFormat::AV_PIX_FMT_BGR444LE as i32,
		BGR444BE      = AVPixelFormat::AV_PIX_FMT_BGR444BE as i32,
		YA8           = AVPixelFormat::AV_PIX_FMT_YA8 as i32,
		BGR48BE       = AVPixelFormat::AV_PIX_FMT_BGR48BE as i32,
		BGR48LE       = AVPixelFormat::AV_PIX_FMT_BGR48LE as i32,
		YUV420P9BE    = AVPixelFormat::AV_PIX_FMT_YUV420P9BE as i32,
		YUV420P9LE    = AVPixelFormat::AV_PIX_FMT_YUV420P9LE as i32,
		YUV420P10BE   = AVPixelFormat::AV_PIX_FMT_YUV420P10BE as i32,
		YUV420P10LE   = AVPixelFormat::AV_PIX_FMT_YUV420P10LE as i32,
		YUV422P10BE   = AVPixelFormat::AV_PIX_FMT_YUV422P10BE as i32,
		YUV422P10LE   = AVPixelFormat::AV_PIX_FMT_YUV422P10LE as i32,
		YUV444P9BE    = AVPixelFormat::AV_PIX_FMT_YUV444P9BE as i32,
		YUV444P9LE    = AVPixelFormat::AV_PIX_FMT_YUV444P9LE as i32,
		YUV444P10BE   = AVPixelFormat::AV_PIX_FMT_YUV444P10BE as i32,
		YUV444P10LE   = AVPixelFormat::AV_PIX_FMT_YUV444P10LE as i32,
		YUV422P9BE    = AVPixelFormat::AV_PIX_FMT_YUV422P9BE as i32,
		YUV422P9LE    = AVPixelFormat::AV_PIX_FMT_YUV422P9LE as i32,
		GBRP          = AVPixelFormat::AV_PIX_FMT_GBRP as i32,
		GBRP9BE       = AVPixelFormat::AV_PIX_FMT_GBRP9BE as i32,
		GBRP9LE       = AVPixelFormat::AV_PIX_FMT_GBRP9LE as i32,
		GBRP10BE      = AVPixelFormat::AV_PIX_FMT_GBRP10BE as i32,
		GBRP10LE      = AVPixelFormat::AV_PIX_FMT_GBRP10LE as i32,
		GBRP16BE      = AVPixelFormat::AV_PIX_FMT_GBRP16BE as i32,
		GBRP16LE      = AVPixelFormat::AV_PIX_FMT_GBRP16LE as i32,
		YUVA422P      = AVPixelFormat::AV_PIX_FMT_YUVA422P as i32,
		YUVA444P      = AVPixelFormat::AV_PIX_FMT_YUVA444P as i32,
		YUVA420P9BE   = AVPixelFormat::AV_PIX_FMT_YUVA420P9BE as i32,
		YUVA420P9LE   = AVPixelFormat::AV_PIX_FMT_YUVA420P9LE as i32,
		YUVA422P9BE   = AVPixelFormat::AV_PIX_FMT_YUVA422P9BE as i32,
		YUVA422P9LE   = AVPixelFormat::AV_PIX_FMT_YUVA422P9LE as i32,
		YUVA444P9BE   = AVPixelFormat::AV_PIX_FMT_YUVA444P9BE as i32,
		YUVA444P9LE   = AVPixelFormat::AV_PIX_FMT_YUVA444P9LE as i32,
		YUVA420P10BE  = AVPixelFormat::AV_PIX_FMT_YUVA420P10BE as i32,
		YUVA420P10LE  = AVPixelFormat::AV_PIX_FMT_YUVA420P10LE as i32,
		YUVA422P10BE  = AVPixelFormat::AV_PIX_FMT_YUVA422P10BE as i32,
		YUVA422P10LE  = AVPixelFormat::AV_PIX_FMT_YUVA422P10LE as i32,
		YUVA444P10BE  = AVPixelFormat::AV_PIX_FMT_YUVA444P10BE as i32,
		YUVA444P10LE  = AVPixelFormat::AV_PIX_FMT_YUVA444P10LE as i32,
		YUVA420P16BE  = AVPixelFormat::AV_PIX_FMT_YUVA420P16BE as i32,
		YUVA420P16LE  = AVPixelFormat::AV_PIX_FMT_YUVA420P16LE as i32,
		YUVA422P16BE  = AVPixelFormat::AV_PIX_FMT_YUVA422P16BE as i32,
		YUVA422P16LE  = AVPixelFormat::AV_PIX_FMT_YUVA422P16LE as i32,
		YUVA444P16BE  = AVPixelFormat::AV_PIX_FMT_YUVA444P16BE as i32,
		YUVA444P16LE  = AVPixelFormat::AV_PIX_FMT_YUVA444P16LE as i32,
		VDPAU         = AVPixelFormat::AV_PIX_FMT_VDPAU as i32,
		XYZ12LE       = AVPixelFormat::AV_PIX_FMT_XYZ12LE as i32,
		XYZ12BE       = AVPixelFormat::AV_PIX_FMT_XYZ12BE as i32,
		NV16          = AVPixelFormat::AV_PIX_FMT_NV16 as i32,
		NV20LE        = AVPixelFormat::AV_PIX_FMT_NV20LE as i32,
		NV20BE        = AVPixelFormat::AV_PIX_FMT_NV20BE as i32,
		RGBA64BE      = AVPixelFormat::AV_PIX_FMT_RGBA64BE as i32,
		RGBA64LE      = AVPixelFormat::AV_PIX_FMT_RGBA64LE as i32,
		BGRA64BE      = AVPixelFormat::AV_PIX_FMT_BGRA64BE as i32,
		BGRA64LE      = AVPixelFormat::AV_PIX_FMT_BGRA64LE as i32,
		YVYU422       = AVPixelFormat::AV_PIX_FMT_YVYU422 as i32,
		YA16BE        = AVPixelFormat::AV_PIX_FMT_YA16BE as i32,
		YA16LE        = AVPixelFormat::AV_PIX_FMT_YA16LE as i32,
		GBRAP         = AVPixelFormat::AV_PIX_FMT_GBRAP as i32,
		GBRAP16BE     = AVPixelFormat::AV_PIX_FMT_GBRAP16BE as i32,
		GBRAP16LE     = AVPixelFormat::AV_PIX_FMT_GBRAP16LE as i32,
		QSV           = AVPixelFormat::AV_PIX_FMT_QSV as i32,
		MMAL          = AVPixelFormat::AV_PIX_FMT_MMAL as i32,
		D3D11VAVld    = AVPixelFormat::AV_PIX_FMT_D3D11VA_VLD as i32,
		CUDA          = AVPixelFormat::AV_PIX_FMT_CUDA as i32,
		ZRGB          = AVPixelFormat::AV_PIX_FMT_0RGB as i32,
		RGBZ          = AVPixelFormat::AV_PIX_FMT_RGB0 as i32,
		ZBGR          = AVPixelFormat::AV_PIX_FMT_0BGR as i32,
		BGR0          = AVPixelFormat::AV_PIX_FMT_BGR0 as i32,
		YUV420P12BE   = AVPixelFormat::AV_PIX_FMT_YUV420P12BE as i32,
		YUV420P12LE   = AVPixelFormat::AV_PIX_FMT_YUV420P12LE as i32,
		YUV420P14BE   = AVPixelFormat::AV_PIX_FMT_YUV420P14BE as i32,
		YUV420P14LE   = AVPixelFormat::AV_PIX_FMT_YUV420P14LE as i32,
		YUV422P12BE   = AVPixelFormat::AV_PIX_FMT_YUV422P12BE as i32,
		YUV422P12LE   = AVPixelFormat::AV_PIX_FMT_YUV422P12LE as i32,
		YUV422P14BE   = AVPixelFormat::AV_PIX_FMT_YUV422P14BE as i32,
		YUV422P14LE   = AVPixelFormat::AV_PIX_FMT_YUV422P14LE as i32,
		YUV444P12BE   = AVPixelFormat::AV_PIX_FMT_YUV444P12BE as i32,
		YUV444P12LE   = AVPixelFormat::AV_PIX_FMT_YUV444P12LE as i32,
		YUV444P14BE   = AVPixelFormat::AV_PIX_FMT_YUV444P14BE as i32,
		YUV444P14LE   = AVPixelFormat::AV_PIX_FMT_YUV444P14LE as i32,
		GBRP12BE      = AVPixelFormat::AV_PIX_FMT_GBRP12BE as i32,
		GBRP12LE      = AVPixelFormat::AV_PIX_FMT_GBRP12LE as i32,
		GBRP14BE      = AVPixelFormat::AV_PIX_FMT_GBRP14BE as i32,
		GBRP14LE      = AVPixelFormat::AV_PIX_FMT_GBRP14LE as i32,
		YUVJ411P      = AVPixelFormat::AV_PIX_FMT_YUVJ411P as i32,
		BayerBGGR8    = AVPixelFormat::AV_PIX_FMT_BAYER_BGGR8 as i32,
		BayerRGGB8    = AVPixelFormat::AV_PIX_FMT_BAYER_RGGB8 as i32,
		BayerGBRG8    = AVPixelFormat::AV_PIX_FMT_BAYER_GBRG8 as i32,
		BayerGRBG8    = AVPixelFormat::AV_PIX_FMT_BAYER_GRBG8 as i32,
		BayerBGGR16LE = AVPixelFormat::AV_PIX_FMT_BAYER_BGGR16LE as i32,
		BayerBGGR16BE = AVPixelFormat::AV_PIX_FMT_BAYER_BGGR16BE as i32,
		BayerRGGB16LE = AVPixelFormat::AV_PIX_FMT_BAYER_RGGB16LE as i32,
		BayerRGGB16BE = AVPixelFormat::AV_PIX_FMT_BAYER_RGGB16BE as i32,
		BayerGBRG16LE = AVPixelFormat::AV_PIX_FMT_BAYER_GBRG16LE as i32,
		BayerGBRG16BE = AVPixelFormat::AV_PIX_FMT_BAYER_GBRG16BE as i32,
		BayerGRBG16LE = AVPixelFormat::AV_PIX_FMT_BAYER_GRBG16LE as i32,
		BayerGRBG16BE = AVPixelFormat::AV_PIX_FMT_BAYER_GRBG16BE as i32,
		XVMC          = AVPixelFormat::AV_PIX_FMT_XVMC as i32,
		YUV440P10LE   = AVPixelFormat::AV_PIX_FMT_YUV440P10LE as i32,
		YUV440P10BE   = AVPixelFormat::AV_PIX_FMT_YUV440P10BE as i32,
		YUV440P12LE   = AVPixelFormat::AV_PIX_FMT_YUV440P12LE as i32,
		YUV440P12BE   = AVPixelFormat::AV_PIX_FMT_YUV440P12BE as i32,
		AYUV64LE      = AVPixelFormat::AV_PIX_FMT_AYUV64LE as i32,
		AYUV64BE      = AVPixelFormat::AV_PIX_FMT_AYUV64BE as i32,
		VIDEOTOOLBOX  = AVPixelFormat::AV_PIX_FMT_VIDEOTOOLBOX as i32,
		P010LE        = AVPixelFormat::AV_PIX_FMT_P010LE as i32,
		P010BE        = AVPixelFormat::AV_PIX_FMT_P010BE as i32,
		GBRAP12BE     = AVPixelFormat::AV_PIX_FMT_GBRAP12BE as i32,
		GBRAP12LE     = AVPixelFormat::AV_PIX_FMT_GBRAP12LE as i32,
		GBRAP10BE     = AVPixelFormat::AV_PIX_FMT_GBRAP10BE as i32,
		GBRAP10LE     = AVPixelFormat::AV_PIX_FMT_GBRAP10LE as i32,
		MEDIACODEC    = AVPixelFormat::AV_PIX_FMT_MEDIACODEC as i32,
		GRAY12BE      = AVPixelFormat::AV_PIX_FMT_GRAY12BE as i32,
		GRAY12LE      = AVPixelFormat::AV_PIX_FMT_GRAY12LE as i32,
		GRAY10BE      = AVPixelFormat::AV_PIX_FMT_GRAY10BE as i32,
		GRAY10LE      = AVPixelFormat::AV_PIX_FMT_GRAY10LE as i32,
		P016LE        = AVPixelFormat::AV_PIX_FMT_P016LE as i32,
		P016BE        = AVPixelFormat::AV_PIX_FMT_P016BE as i32,
		D3D11         = AVPixelFormat::AV_PIX_FMT_D3D11 as i32,
		GRAY9BE       = AVPixelFormat::AV_PIX_FMT_GRAY9BE as i32,
		GRAY9LE       = AVPixelFormat::AV_PIX_FMT_GRAY9LE as i32,
		GBRPF32BE     = AVPixelFormat::AV_PIX_FMT_GBRPF32BE as i32,
		GBRPF32LE     = AVPixelFormat::AV_PIX_FMT_GBRPF32LE as i32,
		GBRAPF32BE    = AVPixelFormat::AV_PIX_FMT_GBRAPF32BE as i32,
		GBRAPF32LE    = AVPixelFormat::AV_PIX_FMT_GBRAPF32LE as i32,
		DRMPRIME      = AVPixelFormat::AV_PIX_FMT_DRM_PRIME as i32,
		OPENCL        = AVPixelFormat::AV_PIX_FMT_OPENCL as i32,
		GRAY14BE      = AVPixelFormat::AV_PIX_FMT_GRAY14BE as i32,
		GRAY14LE      = AVPixelFormat::AV_PIX_FMT_GRAY14LE as i32,
		GRAYF32BE     = AVPixelFormat::AV_PIX_FMT_GRAYF32BE as i32,
		GRAYF32LE     = AVPixelFormat::AV_PIX_FMT_GRAYF32LE as i32,
		YUVA422P12BE  = AVPixelFormat::AV_PIX_FMT_YUVA422P12BE as i32,
		YUVA422P12LE  = AVPixelFormat::AV_PIX_FMT_YUVA422P12LE as i32,
		YUVA444P12BE  = AVPixelFormat::AV_PIX_FMT_YUVA444P12BE as i32,
		YUVA444P12LE  = AVPixelFormat::AV_PIX_FMT_YUVA444P12LE as i32,
		NV24          = AVPixelFormat::AV_PIX_FMT_NV24 as i32,
		NV42          = AVPixelFormat::AV_PIX_FMT_NV42 as i32,
		VULKAN        = AVPixelFormat::AV_PIX_FMT_VULKAN as i32,
		Y210BE        = AVPixelFormat::AV_PIX_FMT_Y210BE as i32,
		Y210LE        = AVPixelFormat::AV_PIX_FMT_Y210LE as i32,
		X2RGB10LE     = AVPixelFormat::AV_PIX_FMT_X2RGB10LE as i32,
		X2RGB10BE     = AVPixelFormat::AV_PIX_FMT_X2RGB10BE as i32,
		X2BGR10LE     = AVPixelFormat::AV_PIX_FMT_X2BGR10LE as i32,
		X2BGR10BE     = AVPixelFormat::AV_PIX_FMT_X2BGR10BE as i32,
		P210BE        = AVPixelFormat::AV_PIX_FMT_P210BE as i32,
		P210LE        = AVPixelFormat::AV_PIX_FMT_P210LE as i32,
		P410BE        = AVPixelFormat::AV_PIX_FMT_P410BE as i32,
		P410LE        = AVPixelFormat::AV_PIX_FMT_P410LE as i32,
		P216BE        = AVPixelFormat::AV_PIX_FMT_P216BE as i32,
		P216LE        = AVPixelFormat::AV_PIX_FMT_P216LE as i32,
		P416BE        = AVPixelFormat::AV_PIX_FMT_P416BE as i32,
		P416LE        = AVPixelFormat::AV_PIX_FMT_P416LE as i32,
		VUYA          = AVPixelFormat::AV_PIX_FMT_VUYA as i32,
		RGBAF16BE     = AVPixelFormat::AV_PIX_FMT_RGBAF16BE as i32,
		RGBAF16LE     = AVPixelFormat::AV_PIX_FMT_RGBAF16LE as i32,
		VUYX          = AVPixelFormat::AV_PIX_FMT_VUYX as i32,
		P012LE        = AVPixelFormat::AV_PIX_FMT_P012LE as i32,
		P012BE        = AVPixelFormat::AV_PIX_FMT_P012BE as i32,
		Y212BE        = AVPixelFormat::AV_PIX_FMT_Y212BE as i32,
		Y212LE        = AVPixelFormat::AV_PIX_FMT_Y212LE as i32,
		XV30BE        = AVPixelFormat::AV_PIX_FMT_XV30BE as i32,
		XV30LE        = AVPixelFormat::AV_PIX_FMT_XV30LE as i32,
		XV36BE        = AVPixelFormat::AV_PIX_FMT_XV36BE as i32,
		XV36LE        = AVPixelFormat::AV_PIX_FMT_XV36LE as i32,
		RGBF32BE      = AVPixelFormat::AV_PIX_FMT_RGBF32BE as i32,
		RGBF32LE      = AVPixelFormat::AV_PIX_FMT_RGBF32LE as i32,
		RGBAF32BE     = AVPixelFormat::AV_PIX_FMT_RGBAF32BE as i32,
		RGBAF32LE     = AVPixelFormat::AV_PIX_FMT_RGBAF32LE as i32,
		P212BE        = AVPixelFormat::AV_PIX_FMT_P212BE as i32,
		P212LE        = AVPixelFormat::AV_PIX_FMT_P212LE as i32,
		P412BE        = AVPixelFormat::AV_PIX_FMT_P412BE as i32,
		P412LE        = AVPixelFormat::AV_PIX_FMT_P412LE as i32,
		GBRAP14BE     = AVPixelFormat::AV_PIX_FMT_GBRAP14BE as i32,
		GBRAP14LE     = AVPixelFormat::AV_PIX_FMT_GBRAP14LE as i32
	}
}

define_av_alias_casts! {
	#[repr(i32)]
	pub enum Discard = AVDiscard {
		#[default]
		None     = AVDiscard::AVDISCARD_NONE as i32,
		Default  = AVDiscard::AVDISCARD_DEFAULT as i32,
		NonRef   = AVDiscard::AVDISCARD_NONREF as i32,
		Bidir    = AVDiscard::AVDISCARD_BIDIR as i32,
		NonIntra = AVDiscard::AVDISCARD_NONINTRA as i32,
		NonKey   = AVDiscard::AVDISCARD_NONKEY as i32,
		All      = AVDiscard::AVDISCARD_ALL as i32
	}
}
