name: Docs

on:
  push:
    branches: [ "main" ]

env:
  FFMPEG_VERSION: ffmpeg-n7.1-latest-linux%ARCH%-lgpl-shared-7.1

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure pages
        uses: actions/configure-pages@v4
      - name: Setup
        run: .github/workflows/install_ffmpeg
      - name: Build docs
        run: |
          cargo doc --no-deps --features xx-doc \
            --package log --package enumflags2 --package num-traits \
            --package xx-macros --package xx-proc-macros --package xx-core \
            --package xx-pulse --package simple-dns --package rustls --package http \
            --package xx-url --package ffmpeg-sys-next --package xx-mpeg
          echo '<meta http-equiv="refresh" content="0; url=xx_mpeg">' > target/doc/index.html
          rm target/doc/.lock
      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
