#!/bin/bash
TARGETARCH=$(uname -p); if [ "$TARGETARCH" = "x86_64" ]; then
	export FFMPEG_ARCH="64";
elif [ "$TARGETARCH" = "aarch64" ]; then
	export FFMPEG_ARCH="arm64";
else
	echo "Unsupported architecture: $TARGETARCH";
	exit 1;
fi

export FFMPEG_BUILD=$(echo "$FFMPEG_VERSION" | sed "s/%ARCH%/$FFMPEG_ARCH/g")

curl -L -O "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/$FFMPEG_BUILD.tar.xz"
tar -xf $FFMPEG_BUILD.tar.xz

rm $FFMPEG_BUILD.tar.xz
mv $FFMPEG_BUILD ffmpeg

sudo cp -r ffmpeg/bin/* /usr/local/bin
sudo cp -r ffmpeg/include/* /usr/local/include
sudo cp -r ffmpeg/lib/* /usr/local/lib
rm -rf ffmpeg

sudo ldconfig
ffmpeg -version